services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  rag-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: rag-challenge-rag-api
    ports:
      - "8000:8000"
    volumes:
      - ./RAG-Challenge:/app/RAG-Challenge
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - ollama
      - qdrant

  ui:
    image: rag-challenge-rag-api
    container_name: rag-ui
    depends_on:
      - rag-api
    environment:
      BACKEND_URL: "http://rag-api:8000"
    working_dir: /app
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "RAG-Challenge/streamlit_app/ui.py",
              "--server.port=8501", "--server.address=0.0.0.0"]

volumes:
  ollama-data:
  qdrant_storage:
