### Upload PDF documents
POST http://localhost:8000/documents
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="Untitled.pdf"
Content-Type: application/pdf

< /Users/bernardozamin/Documents/RAG-Challenge/Untitled.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

### Ask a question
POST http://localhost:8000/question
Content-Type: application/json

{
  "question": "What is the text about?"
}

### Ask a question
POST http://localhost:8000/question
Content-Type: application/json

{
  "question": "Qual a cor do ceu"
}