### Upload PDF documents
POST http://localhost:8000/documents
Content-Type: multipart/form-data

files=/Users/bernardozamin/Downloads/TRACTIAN/case_files/LB5001.pdf

###

### Ask a question
POST http://localhost:8000/question
Content-Type: application/json

{
  "question": "What is the color of the sky?"
}


